version: "3.1"

services:
  db_graphql:
    image: postgres:13-alpine
    env_file:
      - envs/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5433:5433'
  app:
    build:
      context: .
    ports:
      - '8000:8000'
    env_file:
      - envs/.env
    volumes:
      - .:/app:rw
    command: [ "sh", "-c", "python3 main.py && alembic upgrade head" ]
    depends_on:
      - db_graphql

volumes:
  postgres_data:
